### ISSUE TITLE
following resource(s) failed to  create: [ServerAlertWaitCondition, ComputeAlertWaitCondition]

### ISSUE THREAD

**Issue by adubrovsky** [aws-quickstart/quickstart-ibm-spectrum-scale#9]
Hello, I am getting CREATE_FAILED due to following resource(s) failed to  create: [ServerAlertWaitCondition, ComputeAlertWaitCondition]

I tried "new VPC" and "existing VPC" templates.
thanks

  | 01:19:11 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | ClusterStack | Embedded  stack  arn:aws:cloudformation:us-east-1:160209456697:stack/scf7-ClusterStack-1NM9PWT7OIA75/97314240-af03-11e7-9221-500c28601499  was not successfully created: The following resource(s) failed to  create: [ServerAlertWaitCondition, ComputeAlertWaitCondition].

01:19:12 UTC-0400 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | scf7 | The following resource(s) failed to create: [ClusterStack]. . Rollback requested by user.
-- | -- | -- | -- | --

**Comment by SpectrumScaleOnAWS** [comment]
There could be few reasons to failed with timeout error, that I can only comment when see the cluster, specially your selected parameters..few reasons to come this errors..
  1) have you entered correct S3 bucket under "SpectrumS3bucket" parameter?, if not please create new S3 bucket and enter this bucket name here and retry!!
  2) have you selected only one AZ on "Availability Zones" parameter where 2 AZ selection is mandatory?, if yes then please select two AZ and retry!!

Please correct your configuration as mentioned above and let us know if still problem persist?

Thanks!!
Dherendra
